# Compute adaptive weights for CNN (by hand)

In [1]:
import numpy as np

* Input là một ma trận 2 chiều 3*3 
* Một lớp convolution filter 2*2 , s = 1 , p = 1
* Một lớp Max-pooling kernel 1*2, s =1 
* Một lớp dense 
* ouput có kích thước là 1*1

In [3]:
inpt = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("input: \n",inpt)

input: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
conv = np.array([[1,0],[1,0]])
print("convolutio: \n",conv)

convolutio: 
 [[1 0]
 [1 0]]


In [57]:
weightdense1 = np.array([1])
weightdense2 = np.array([4])
print("weight dense: ", weightdense1,weightdense2)

weight dense:  [1] [4]


In [21]:
# ket qua khi qua convolution
for i in range(3-2+1): # theo chiều ngang
    for j in range(3-2+1): # theo chiều doc
        print(np.sum(np.matmul(inpt[j:j+2,i:i+2],conv)))

12
24
16
28


In [26]:
# ket qua sau conv
out_conv = np.array([[12,16],[24,28]])
out_conv

array([[12, 16],
       [24, 28]])

In [56]:
# sau khi qua max-pooling filter 1*2 
pooling = np.amax(out_conv,axis = 1)
pooling

array([16, 28])

In [62]:
# output cuối cùng
np.sum(np.multiply(weightdense1,pooling)) + np.sum(np.multiply(weightdense2,pooling))

220